package com.example.demo.domain.mapper;

import com.example.demo.domain.model.MstDevice;
import com.example.demo.domain.model.MstDeviceExample;
import java.util.Collection;
import java.util.List;
import java.util.Optional;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectProvider;
import org.mybatis.dynamic.sql.SqlColumn;
import org.mybatis.dynamic.sql.SqlTable;
import org.mybatis.dynamic.sql.select.render.SelectStatementProvider;
import org.mybatis.dynamic.sql.util.SqlProviderAdapter;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Service;

@Mapper
public interface MstDeviceMapper {
	
    long countByExample(MstDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_device
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    int deleteByExample(MstDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_device
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    int deleteByPrimaryKey(String device_no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_device
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    int insert(MstDevice row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_device
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    int insertSelective(MstDevice row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_device
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    List<MstDevice> selectByExample(MstDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_device
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    MstDevice selectByPrimaryKey(String device_no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_device
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    int updateByExampleSelective(@Param("row") MstDevice row, @Param("example") MstDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_device
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    int updateByExample(@Param("row") MstDevice row, @Param("example") MstDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_device
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    int updateByPrimaryKeySelective(MstDevice row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_device
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    int updateByPrimaryKey(MstDevice row);
    
    List<MstDevice> selectAll();
    
    List<MstDevice> selectForLeaseList();
    
    MstDevice selectByDeviceNo(String deviceNo);
    
    int update(MstDevice row);
    
    int deleteByDeviceNo(String deviceNo);
    
    MstDevice selectForLeaseDetail(String deviceNo);
    
    int insertDevice(MstDevice row);
    
    int logicalDeleteByDeviceNo(String deviceNo);
}