package com.example.demo.domain.mapper;

import com.example.demo.domain.model.MstUser;
import com.example.demo.domain.model.MstUserExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface MstUserMapper {
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated Tue Apr 16 08:58:15 JST 2024
     */
    long countByExample(MstUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated Tue Apr 16 08:58:15 JST 2024
     */
    int deleteByExample(MstUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated Tue Apr 16 08:58:15 JST 2024
     */
    int deleteByPrimaryKey(String employee_no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated Tue Apr 16 08:58:15 JST 2024
     */
    int insert(MstUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated Tue Apr 16 08:58:15 JST 2024
     */
    int insertSelective(MstUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated Tue Apr 16 08:58:15 JST 2024
     */
    List<MstUser> selectByExample(MstUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated Tue Apr 16 08:58:15 JST 2024
     */
    MstUser selectByPrimaryKey(String employee_no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated Tue Apr 16 08:58:15 JST 2024
     */
    int updateByExampleSelective(@Param("row") MstUser row, @Param("example") MstUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated Tue Apr 16 08:58:15 JST 2024
     */
    int updateByExample(@Param("row") MstUser row, @Param("example") MstUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated Tue Apr 16 08:58:15 JST 2024
     */
    int updateByPrimaryKeySelective(MstUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated Tue Apr 16 08:58:15 JST 2024
     */
    int updateByPrimaryKey(MstUser row);
    
    List<MstUser> selectAll();
    
    MstUser selectByEmployeeNo(String employeeNo);
    
    MstUser selectName();
    
    int insertUser(MstUser row);
    
    int deleteByEmployeeNo(String employeeNo);
    
    int update(MstUser row);
}