package com.example.demo.domain.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class MstDeviceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mst_device
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mst_device
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mst_device
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_device
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    public MstDeviceExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_device
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_device
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_device
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_device
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_device
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_device
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_device
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_device
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_device
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_device
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mst_device
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andDevice_noIsNull() {
            addCriterion("device_no is null");
            return (Criteria) this;
        }

        public Criteria andDevice_noIsNotNull() {
            addCriterion("device_no is not null");
            return (Criteria) this;
        }

        public Criteria andDevice_noEqualTo(String value) {
            addCriterion("device_no =", value, "device_no");
            return (Criteria) this;
        }

        public Criteria andDevice_noNotEqualTo(String value) {
            addCriterion("device_no <>", value, "device_no");
            return (Criteria) this;
        }

        public Criteria andDevice_noGreaterThan(String value) {
            addCriterion("device_no >", value, "device_no");
            return (Criteria) this;
        }

        public Criteria andDevice_noGreaterThanOrEqualTo(String value) {
            addCriterion("device_no >=", value, "device_no");
            return (Criteria) this;
        }

        public Criteria andDevice_noLessThan(String value) {
            addCriterion("device_no <", value, "device_no");
            return (Criteria) this;
        }

        public Criteria andDevice_noLessThanOrEqualTo(String value) {
            addCriterion("device_no <=", value, "device_no");
            return (Criteria) this;
        }

        public Criteria andDevice_noLike(String value) {
            addCriterion("device_no like", value, "device_no");
            return (Criteria) this;
        }

        public Criteria andDevice_noNotLike(String value) {
            addCriterion("device_no not like", value, "device_no");
            return (Criteria) this;
        }

        public Criteria andDevice_noIn(List<String> values) {
            addCriterion("device_no in", values, "device_no");
            return (Criteria) this;
        }

        public Criteria andDevice_noNotIn(List<String> values) {
            addCriterion("device_no not in", values, "device_no");
            return (Criteria) this;
        }

        public Criteria andDevice_noBetween(String value1, String value2) {
            addCriterion("device_no between", value1, value2, "device_no");
            return (Criteria) this;
        }

        public Criteria andDevice_noNotBetween(String value1, String value2) {
            addCriterion("device_no not between", value1, value2, "device_no");
            return (Criteria) this;
        }

        public Criteria andMakerIsNull() {
            addCriterion("maker is null");
            return (Criteria) this;
        }

        public Criteria andMakerIsNotNull() {
            addCriterion("maker is not null");
            return (Criteria) this;
        }

        public Criteria andMakerEqualTo(String value) {
            addCriterion("maker =", value, "maker");
            return (Criteria) this;
        }

        public Criteria andMakerNotEqualTo(String value) {
            addCriterion("maker <>", value, "maker");
            return (Criteria) this;
        }

        public Criteria andMakerGreaterThan(String value) {
            addCriterion("maker >", value, "maker");
            return (Criteria) this;
        }

        public Criteria andMakerGreaterThanOrEqualTo(String value) {
            addCriterion("maker >=", value, "maker");
            return (Criteria) this;
        }

        public Criteria andMakerLessThan(String value) {
            addCriterion("maker <", value, "maker");
            return (Criteria) this;
        }

        public Criteria andMakerLessThanOrEqualTo(String value) {
            addCriterion("maker <=", value, "maker");
            return (Criteria) this;
        }

        public Criteria andMakerLike(String value) {
            addCriterion("maker like", value, "maker");
            return (Criteria) this;
        }

        public Criteria andMakerNotLike(String value) {
            addCriterion("maker not like", value, "maker");
            return (Criteria) this;
        }

        public Criteria andMakerIn(List<String> values) {
            addCriterion("maker in", values, "maker");
            return (Criteria) this;
        }

        public Criteria andMakerNotIn(List<String> values) {
            addCriterion("maker not in", values, "maker");
            return (Criteria) this;
        }

        public Criteria andMakerBetween(String value1, String value2) {
            addCriterion("maker between", value1, value2, "maker");
            return (Criteria) this;
        }

        public Criteria andMakerNotBetween(String value1, String value2) {
            addCriterion("maker not between", value1, value2, "maker");
            return (Criteria) this;
        }

        public Criteria andOsIsNull() {
            addCriterion("os is null");
            return (Criteria) this;
        }

        public Criteria andOsIsNotNull() {
            addCriterion("os is not null");
            return (Criteria) this;
        }

        public Criteria andOsEqualTo(String value) {
            addCriterion("os =", value, "os");
            return (Criteria) this;
        }

        public Criteria andOsNotEqualTo(String value) {
            addCriterion("os <>", value, "os");
            return (Criteria) this;
        }

        public Criteria andOsGreaterThan(String value) {
            addCriterion("os >", value, "os");
            return (Criteria) this;
        }

        public Criteria andOsGreaterThanOrEqualTo(String value) {
            addCriterion("os >=", value, "os");
            return (Criteria) this;
        }

        public Criteria andOsLessThan(String value) {
            addCriterion("os <", value, "os");
            return (Criteria) this;
        }

        public Criteria andOsLessThanOrEqualTo(String value) {
            addCriterion("os <=", value, "os");
            return (Criteria) this;
        }

        public Criteria andOsLike(String value) {
            addCriterion("os like", value, "os");
            return (Criteria) this;
        }

        public Criteria andOsNotLike(String value) {
            addCriterion("os not like", value, "os");
            return (Criteria) this;
        }

        public Criteria andOsIn(List<String> values) {
            addCriterion("os in", values, "os");
            return (Criteria) this;
        }

        public Criteria andOsNotIn(List<String> values) {
            addCriterion("os not in", values, "os");
            return (Criteria) this;
        }

        public Criteria andOsBetween(String value1, String value2) {
            addCriterion("os between", value1, value2, "os");
            return (Criteria) this;
        }

        public Criteria andOsNotBetween(String value1, String value2) {
            addCriterion("os not between", value1, value2, "os");
            return (Criteria) this;
        }

        public Criteria andMemoryIsNull() {
            addCriterion("memory is null");
            return (Criteria) this;
        }

        public Criteria andMemoryIsNotNull() {
            addCriterion("memory is not null");
            return (Criteria) this;
        }

        public Criteria andMemoryEqualTo(String value) {
            addCriterion("memory =", value, "memory");
            return (Criteria) this;
        }

        public Criteria andMemoryNotEqualTo(String value) {
            addCriterion("memory <>", value, "memory");
            return (Criteria) this;
        }

        public Criteria andMemoryGreaterThan(String value) {
            addCriterion("memory >", value, "memory");
            return (Criteria) this;
        }

        public Criteria andMemoryGreaterThanOrEqualTo(String value) {
            addCriterion("memory >=", value, "memory");
            return (Criteria) this;
        }

        public Criteria andMemoryLessThan(String value) {
            addCriterion("memory <", value, "memory");
            return (Criteria) this;
        }

        public Criteria andMemoryLessThanOrEqualTo(String value) {
            addCriterion("memory <=", value, "memory");
            return (Criteria) this;
        }

        public Criteria andMemoryLike(String value) {
            addCriterion("memory like", value, "memory");
            return (Criteria) this;
        }

        public Criteria andMemoryNotLike(String value) {
            addCriterion("memory not like", value, "memory");
            return (Criteria) this;
        }

        public Criteria andMemoryIn(List<String> values) {
            addCriterion("memory in", values, "memory");
            return (Criteria) this;
        }

        public Criteria andMemoryNotIn(List<String> values) {
            addCriterion("memory not in", values, "memory");
            return (Criteria) this;
        }

        public Criteria andMemoryBetween(String value1, String value2) {
            addCriterion("memory between", value1, value2, "memory");
            return (Criteria) this;
        }

        public Criteria andMemoryNotBetween(String value1, String value2) {
            addCriterion("memory not between", value1, value2, "memory");
            return (Criteria) this;
        }

        public Criteria andCapacityIsNull() {
            addCriterion("capacity is null");
            return (Criteria) this;
        }

        public Criteria andCapacityIsNotNull() {
            addCriterion("capacity is not null");
            return (Criteria) this;
        }

        public Criteria andCapacityEqualTo(String value) {
            addCriterion("capacity =", value, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityNotEqualTo(String value) {
            addCriterion("capacity <>", value, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityGreaterThan(String value) {
            addCriterion("capacity >", value, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityGreaterThanOrEqualTo(String value) {
            addCriterion("capacity >=", value, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityLessThan(String value) {
            addCriterion("capacity <", value, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityLessThanOrEqualTo(String value) {
            addCriterion("capacity <=", value, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityLike(String value) {
            addCriterion("capacity like", value, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityNotLike(String value) {
            addCriterion("capacity not like", value, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityIn(List<String> values) {
            addCriterion("capacity in", values, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityNotIn(List<String> values) {
            addCriterion("capacity not in", values, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityBetween(String value1, String value2) {
            addCriterion("capacity between", value1, value2, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityNotBetween(String value1, String value2) {
            addCriterion("capacity not between", value1, value2, "capacity");
            return (Criteria) this;
        }

        public Criteria andGraphic_boardIsNull() {
            addCriterion("graphic_board is null");
            return (Criteria) this;
        }

        public Criteria andGraphic_boardIsNotNull() {
            addCriterion("graphic_board is not null");
            return (Criteria) this;
        }

        public Criteria andGraphic_boardEqualTo(String value) {
            addCriterion("graphic_board =", value, "graphic_board");
            return (Criteria) this;
        }

        public Criteria andGraphic_boardNotEqualTo(String value) {
            addCriterion("graphic_board <>", value, "graphic_board");
            return (Criteria) this;
        }

        public Criteria andGraphic_boardGreaterThan(String value) {
            addCriterion("graphic_board >", value, "graphic_board");
            return (Criteria) this;
        }

        public Criteria andGraphic_boardGreaterThanOrEqualTo(String value) {
            addCriterion("graphic_board >=", value, "graphic_board");
            return (Criteria) this;
        }

        public Criteria andGraphic_boardLessThan(String value) {
            addCriterion("graphic_board <", value, "graphic_board");
            return (Criteria) this;
        }

        public Criteria andGraphic_boardLessThanOrEqualTo(String value) {
            addCriterion("graphic_board <=", value, "graphic_board");
            return (Criteria) this;
        }

        public Criteria andGraphic_boardLike(String value) {
            addCriterion("graphic_board like", value, "graphic_board");
            return (Criteria) this;
        }

        public Criteria andGraphic_boardNotLike(String value) {
            addCriterion("graphic_board not like", value, "graphic_board");
            return (Criteria) this;
        }

        public Criteria andGraphic_boardIn(List<String> values) {
            addCriterion("graphic_board in", values, "graphic_board");
            return (Criteria) this;
        }

        public Criteria andGraphic_boardNotIn(List<String> values) {
            addCriterion("graphic_board not in", values, "graphic_board");
            return (Criteria) this;
        }

        public Criteria andGraphic_boardBetween(String value1, String value2) {
            addCriterion("graphic_board between", value1, value2, "graphic_board");
            return (Criteria) this;
        }

        public Criteria andGraphic_boardNotBetween(String value1, String value2) {
            addCriterion("graphic_board not between", value1, value2, "graphic_board");
            return (Criteria) this;
        }

        public Criteria andStorage_locateIsNull() {
            addCriterion("storage_locate is null");
            return (Criteria) this;
        }

        public Criteria andStorage_locateIsNotNull() {
            addCriterion("storage_locate is not null");
            return (Criteria) this;
        }

        public Criteria andStorage_locateEqualTo(String value) {
            addCriterion("storage_locate =", value, "storage_locate");
            return (Criteria) this;
        }

        public Criteria andStorage_locateNotEqualTo(String value) {
            addCriterion("storage_locate <>", value, "storage_locate");
            return (Criteria) this;
        }

        public Criteria andStorage_locateGreaterThan(String value) {
            addCriterion("storage_locate >", value, "storage_locate");
            return (Criteria) this;
        }

        public Criteria andStorage_locateGreaterThanOrEqualTo(String value) {
            addCriterion("storage_locate >=", value, "storage_locate");
            return (Criteria) this;
        }

        public Criteria andStorage_locateLessThan(String value) {
            addCriterion("storage_locate <", value, "storage_locate");
            return (Criteria) this;
        }

        public Criteria andStorage_locateLessThanOrEqualTo(String value) {
            addCriterion("storage_locate <=", value, "storage_locate");
            return (Criteria) this;
        }

        public Criteria andStorage_locateLike(String value) {
            addCriterion("storage_locate like", value, "storage_locate");
            return (Criteria) this;
        }

        public Criteria andStorage_locateNotLike(String value) {
            addCriterion("storage_locate not like", value, "storage_locate");
            return (Criteria) this;
        }

        public Criteria andStorage_locateIn(List<String> values) {
            addCriterion("storage_locate in", values, "storage_locate");
            return (Criteria) this;
        }

        public Criteria andStorage_locateNotIn(List<String> values) {
            addCriterion("storage_locate not in", values, "storage_locate");
            return (Criteria) this;
        }

        public Criteria andStorage_locateBetween(String value1, String value2) {
            addCriterion("storage_locate between", value1, value2, "storage_locate");
            return (Criteria) this;
        }

        public Criteria andStorage_locateNotBetween(String value1, String value2) {
            addCriterion("storage_locate not between", value1, value2, "storage_locate");
            return (Criteria) this;
        }

        public Criteria andBrokenIsNull() {
            addCriterion("broken is null");
            return (Criteria) this;
        }

        public Criteria andBrokenIsNotNull() {
            addCriterion("broken is not null");
            return (Criteria) this;
        }

        public Criteria andBrokenEqualTo(Boolean value) {
            addCriterion("broken =", value, "broken");
            return (Criteria) this;
        }

        public Criteria andBrokenNotEqualTo(Boolean value) {
            addCriterion("broken <>", value, "broken");
            return (Criteria) this;
        }

        public Criteria andBrokenGreaterThan(Boolean value) {
            addCriterion("broken >", value, "broken");
            return (Criteria) this;
        }

        public Criteria andBrokenGreaterThanOrEqualTo(Boolean value) {
            addCriterion("broken >=", value, "broken");
            return (Criteria) this;
        }

        public Criteria andBrokenLessThan(Boolean value) {
            addCriterion("broken <", value, "broken");
            return (Criteria) this;
        }

        public Criteria andBrokenLessThanOrEqualTo(Boolean value) {
            addCriterion("broken <=", value, "broken");
            return (Criteria) this;
        }

        public Criteria andBrokenIn(List<Boolean> values) {
            addCriterion("broken in", values, "broken");
            return (Criteria) this;
        }

        public Criteria andBrokenNotIn(List<Boolean> values) {
            addCriterion("broken not in", values, "broken");
            return (Criteria) this;
        }

        public Criteria andBrokenBetween(Boolean value1, Boolean value2) {
            addCriterion("broken between", value1, value2, "broken");
            return (Criteria) this;
        }

        public Criteria andBrokenNotBetween(Boolean value1, Boolean value2) {
            addCriterion("broken not between", value1, value2, "broken");
            return (Criteria) this;
        }

        public Criteria andLease_flagIsNull() {
            addCriterion("lease_flag is null");
            return (Criteria) this;
        }

        public Criteria andLease_flagIsNotNull() {
            addCriterion("lease_flag is not null");
            return (Criteria) this;
        }

        public Criteria andLease_flagEqualTo(Boolean value) {
            addCriterion("lease_flag =", value, "lease_flag");
            return (Criteria) this;
        }

        public Criteria andLease_flagNotEqualTo(Boolean value) {
            addCriterion("lease_flag <>", value, "lease_flag");
            return (Criteria) this;
        }

        public Criteria andLease_flagGreaterThan(Boolean value) {
            addCriterion("lease_flag >", value, "lease_flag");
            return (Criteria) this;
        }

        public Criteria andLease_flagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("lease_flag >=", value, "lease_flag");
            return (Criteria) this;
        }

        public Criteria andLease_flagLessThan(Boolean value) {
            addCriterion("lease_flag <", value, "lease_flag");
            return (Criteria) this;
        }

        public Criteria andLease_flagLessThanOrEqualTo(Boolean value) {
            addCriterion("lease_flag <=", value, "lease_flag");
            return (Criteria) this;
        }

        public Criteria andLease_flagIn(List<Boolean> values) {
            addCriterion("lease_flag in", values, "lease_flag");
            return (Criteria) this;
        }

        public Criteria andLease_flagNotIn(List<Boolean> values) {
            addCriterion("lease_flag not in", values, "lease_flag");
            return (Criteria) this;
        }

        public Criteria andLease_flagBetween(Boolean value1, Boolean value2) {
            addCriterion("lease_flag between", value1, value2, "lease_flag");
            return (Criteria) this;
        }

        public Criteria andLease_flagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("lease_flag not between", value1, value2, "lease_flag");
            return (Criteria) this;
        }

        public Criteria andLease_start_dateIsNull() {
            addCriterion("lease_start_date is null");
            return (Criteria) this;
        }

        public Criteria andLease_start_dateIsNotNull() {
            addCriterion("lease_start_date is not null");
            return (Criteria) this;
        }

        public Criteria andLease_start_dateEqualTo(Date value) {
            addCriterionForJDBCDate("lease_start_date =", value, "lease_start_date");
            return (Criteria) this;
        }

        public Criteria andLease_start_dateNotEqualTo(Date value) {
            addCriterionForJDBCDate("lease_start_date <>", value, "lease_start_date");
            return (Criteria) this;
        }

        public Criteria andLease_start_dateGreaterThan(Date value) {
            addCriterionForJDBCDate("lease_start_date >", value, "lease_start_date");
            return (Criteria) this;
        }

        public Criteria andLease_start_dateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("lease_start_date >=", value, "lease_start_date");
            return (Criteria) this;
        }

        public Criteria andLease_start_dateLessThan(Date value) {
            addCriterionForJDBCDate("lease_start_date <", value, "lease_start_date");
            return (Criteria) this;
        }

        public Criteria andLease_start_dateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("lease_start_date <=", value, "lease_start_date");
            return (Criteria) this;
        }

        public Criteria andLease_start_dateIn(List<Date> values) {
            addCriterionForJDBCDate("lease_start_date in", values, "lease_start_date");
            return (Criteria) this;
        }

        public Criteria andLease_start_dateNotIn(List<Date> values) {
            addCriterionForJDBCDate("lease_start_date not in", values, "lease_start_date");
            return (Criteria) this;
        }

        public Criteria andLease_start_dateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("lease_start_date between", value1, value2, "lease_start_date");
            return (Criteria) this;
        }

        public Criteria andLease_start_dateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("lease_start_date not between", value1, value2, "lease_start_date");
            return (Criteria) this;
        }

        public Criteria andLease_deadline_dateIsNull() {
            addCriterion("lease_deadline_date is null");
            return (Criteria) this;
        }

        public Criteria andLease_deadline_dateIsNotNull() {
            addCriterion("lease_deadline_date is not null");
            return (Criteria) this;
        }

        public Criteria andLease_deadline_dateEqualTo(Date value) {
            addCriterionForJDBCDate("lease_deadline_date =", value, "lease_deadline_date");
            return (Criteria) this;
        }

        public Criteria andLease_deadline_dateNotEqualTo(Date value) {
            addCriterionForJDBCDate("lease_deadline_date <>", value, "lease_deadline_date");
            return (Criteria) this;
        }

        public Criteria andLease_deadline_dateGreaterThan(Date value) {
            addCriterionForJDBCDate("lease_deadline_date >", value, "lease_deadline_date");
            return (Criteria) this;
        }

        public Criteria andLease_deadline_dateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("lease_deadline_date >=", value, "lease_deadline_date");
            return (Criteria) this;
        }

        public Criteria andLease_deadline_dateLessThan(Date value) {
            addCriterionForJDBCDate("lease_deadline_date <", value, "lease_deadline_date");
            return (Criteria) this;
        }

        public Criteria andLease_deadline_dateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("lease_deadline_date <=", value, "lease_deadline_date");
            return (Criteria) this;
        }

        public Criteria andLease_deadline_dateIn(List<Date> values) {
            addCriterionForJDBCDate("lease_deadline_date in", values, "lease_deadline_date");
            return (Criteria) this;
        }

        public Criteria andLease_deadline_dateNotIn(List<Date> values) {
            addCriterionForJDBCDate("lease_deadline_date not in", values, "lease_deadline_date");
            return (Criteria) this;
        }

        public Criteria andLease_deadline_dateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("lease_deadline_date between", value1, value2, "lease_deadline_date");
            return (Criteria) this;
        }

        public Criteria andLease_deadline_dateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("lease_deadline_date not between", value1, value2, "lease_deadline_date");
            return (Criteria) this;
        }

        public Criteria andLease_employee_noIsNull() {
            addCriterion("lease_employee_no is null");
            return (Criteria) this;
        }

        public Criteria andLease_employee_noIsNotNull() {
            addCriterion("lease_employee_no is not null");
            return (Criteria) this;
        }

        public Criteria andLease_employee_noEqualTo(String value) {
            addCriterion("lease_employee_no =", value, "lease_employee_no");
            return (Criteria) this;
        }

        public Criteria andLease_employee_noNotEqualTo(String value) {
            addCriterion("lease_employee_no <>", value, "lease_employee_no");
            return (Criteria) this;
        }

        public Criteria andLease_employee_noGreaterThan(String value) {
            addCriterion("lease_employee_no >", value, "lease_employee_no");
            return (Criteria) this;
        }

        public Criteria andLease_employee_noGreaterThanOrEqualTo(String value) {
            addCriterion("lease_employee_no >=", value, "lease_employee_no");
            return (Criteria) this;
        }

        public Criteria andLease_employee_noLessThan(String value) {
            addCriterion("lease_employee_no <", value, "lease_employee_no");
            return (Criteria) this;
        }

        public Criteria andLease_employee_noLessThanOrEqualTo(String value) {
            addCriterion("lease_employee_no <=", value, "lease_employee_no");
            return (Criteria) this;
        }

        public Criteria andLease_employee_noLike(String value) {
            addCriterion("lease_employee_no like", value, "lease_employee_no");
            return (Criteria) this;
        }

        public Criteria andLease_employee_noNotLike(String value) {
            addCriterion("lease_employee_no not like", value, "lease_employee_no");
            return (Criteria) this;
        }

        public Criteria andLease_employee_noIn(List<String> values) {
            addCriterion("lease_employee_no in", values, "lease_employee_no");
            return (Criteria) this;
        }

        public Criteria andLease_employee_noNotIn(List<String> values) {
            addCriterion("lease_employee_no not in", values, "lease_employee_no");
            return (Criteria) this;
        }

        public Criteria andLease_employee_noBetween(String value1, String value2) {
            addCriterion("lease_employee_no between", value1, value2, "lease_employee_no");
            return (Criteria) this;
        }

        public Criteria andLease_employee_noNotBetween(String value1, String value2) {
            addCriterion("lease_employee_no not between", value1, value2, "lease_employee_no");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNull() {
            addCriterion("remarks is null");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNotNull() {
            addCriterion("remarks is not null");
            return (Criteria) this;
        }

        public Criteria andRemarksEqualTo(String value) {
            addCriterion("remarks =", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotEqualTo(String value) {
            addCriterion("remarks <>", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThan(String value) {
            addCriterion("remarks >", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("remarks >=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThan(String value) {
            addCriterion("remarks <", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThanOrEqualTo(String value) {
            addCriterion("remarks <=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLike(String value) {
            addCriterion("remarks like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotLike(String value) {
            addCriterion("remarks not like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksIn(List<String> values) {
            addCriterion("remarks in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotIn(List<String> values) {
            addCriterion("remarks not in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksBetween(String value1, String value2) {
            addCriterion("remarks between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotBetween(String value1, String value2) {
            addCriterion("remarks not between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andInventory_dateIsNull() {
            addCriterion("inventory_date is null");
            return (Criteria) this;
        }

        public Criteria andInventory_dateIsNotNull() {
            addCriterion("inventory_date is not null");
            return (Criteria) this;
        }

        public Criteria andInventory_dateEqualTo(Date value) {
            addCriterionForJDBCDate("inventory_date =", value, "inventory_date");
            return (Criteria) this;
        }

        public Criteria andInventory_dateNotEqualTo(Date value) {
            addCriterionForJDBCDate("inventory_date <>", value, "inventory_date");
            return (Criteria) this;
        }

        public Criteria andInventory_dateGreaterThan(Date value) {
            addCriterionForJDBCDate("inventory_date >", value, "inventory_date");
            return (Criteria) this;
        }

        public Criteria andInventory_dateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("inventory_date >=", value, "inventory_date");
            return (Criteria) this;
        }

        public Criteria andInventory_dateLessThan(Date value) {
            addCriterionForJDBCDate("inventory_date <", value, "inventory_date");
            return (Criteria) this;
        }

        public Criteria andInventory_dateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("inventory_date <=", value, "inventory_date");
            return (Criteria) this;
        }

        public Criteria andInventory_dateIn(List<Date> values) {
            addCriterionForJDBCDate("inventory_date in", values, "inventory_date");
            return (Criteria) this;
        }

        public Criteria andInventory_dateNotIn(List<Date> values) {
            addCriterionForJDBCDate("inventory_date not in", values, "inventory_date");
            return (Criteria) this;
        }

        public Criteria andInventory_dateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("inventory_date between", value1, value2, "inventory_date");
            return (Criteria) this;
        }

        public Criteria andInventory_dateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("inventory_date not between", value1, value2, "inventory_date");
            return (Criteria) this;
        }

        public Criteria andRegister_dateIsNull() {
            addCriterion("register_date is null");
            return (Criteria) this;
        }

        public Criteria andRegister_dateIsNotNull() {
            addCriterion("register_date is not null");
            return (Criteria) this;
        }

        public Criteria andRegister_dateEqualTo(Date value) {
            addCriterionForJDBCDate("register_date =", value, "register_date");
            return (Criteria) this;
        }

        public Criteria andRegister_dateNotEqualTo(Date value) {
            addCriterionForJDBCDate("register_date <>", value, "register_date");
            return (Criteria) this;
        }

        public Criteria andRegister_dateGreaterThan(Date value) {
            addCriterionForJDBCDate("register_date >", value, "register_date");
            return (Criteria) this;
        }

        public Criteria andRegister_dateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("register_date >=", value, "register_date");
            return (Criteria) this;
        }

        public Criteria andRegister_dateLessThan(Date value) {
            addCriterionForJDBCDate("register_date <", value, "register_date");
            return (Criteria) this;
        }

        public Criteria andRegister_dateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("register_date <=", value, "register_date");
            return (Criteria) this;
        }

        public Criteria andRegister_dateIn(List<Date> values) {
            addCriterionForJDBCDate("register_date in", values, "register_date");
            return (Criteria) this;
        }

        public Criteria andRegister_dateNotIn(List<Date> values) {
            addCriterionForJDBCDate("register_date not in", values, "register_date");
            return (Criteria) this;
        }

        public Criteria andRegister_dateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("register_date between", value1, value2, "register_date");
            return (Criteria) this;
        }

        public Criteria andRegister_dateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("register_date not between", value1, value2, "register_date");
            return (Criteria) this;
        }

        public Criteria andUpdate_dateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdate_dateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdate_dateEqualTo(Date value) {
            addCriterionForJDBCDate("update_date =", value, "update_date");
            return (Criteria) this;
        }

        public Criteria andUpdate_dateNotEqualTo(Date value) {
            addCriterionForJDBCDate("update_date <>", value, "update_date");
            return (Criteria) this;
        }

        public Criteria andUpdate_dateGreaterThan(Date value) {
            addCriterionForJDBCDate("update_date >", value, "update_date");
            return (Criteria) this;
        }

        public Criteria andUpdate_dateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("update_date >=", value, "update_date");
            return (Criteria) this;
        }

        public Criteria andUpdate_dateLessThan(Date value) {
            addCriterionForJDBCDate("update_date <", value, "update_date");
            return (Criteria) this;
        }

        public Criteria andUpdate_dateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("update_date <=", value, "update_date");
            return (Criteria) this;
        }

        public Criteria andUpdate_dateIn(List<Date> values) {
            addCriterionForJDBCDate("update_date in", values, "update_date");
            return (Criteria) this;
        }

        public Criteria andUpdate_dateNotIn(List<Date> values) {
            addCriterionForJDBCDate("update_date not in", values, "update_date");
            return (Criteria) this;
        }

        public Criteria andUpdate_dateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("update_date between", value1, value2, "update_date");
            return (Criteria) this;
        }

        public Criteria andUpdate_dateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("update_date not between", value1, value2, "update_date");
            return (Criteria) this;
        }

        public Criteria andDelete_flagIsNull() {
            addCriterion("delete_flag is null");
            return (Criteria) this;
        }

        public Criteria andDelete_flagIsNotNull() {
            addCriterion("delete_flag is not null");
            return (Criteria) this;
        }

        public Criteria andDelete_flagEqualTo(Boolean value) {
            addCriterion("delete_flag =", value, "delete_flag");
            return (Criteria) this;
        }

        public Criteria andDelete_flagNotEqualTo(Boolean value) {
            addCriterion("delete_flag <>", value, "delete_flag");
            return (Criteria) this;
        }

        public Criteria andDelete_flagGreaterThan(Boolean value) {
            addCriterion("delete_flag >", value, "delete_flag");
            return (Criteria) this;
        }

        public Criteria andDelete_flagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("delete_flag >=", value, "delete_flag");
            return (Criteria) this;
        }

        public Criteria andDelete_flagLessThan(Boolean value) {
            addCriterion("delete_flag <", value, "delete_flag");
            return (Criteria) this;
        }

        public Criteria andDelete_flagLessThanOrEqualTo(Boolean value) {
            addCriterion("delete_flag <=", value, "delete_flag");
            return (Criteria) this;
        }

        public Criteria andDelete_flagIn(List<Boolean> values) {
            addCriterion("delete_flag in", values, "delete_flag");
            return (Criteria) this;
        }

        public Criteria andDelete_flagNotIn(List<Boolean> values) {
            addCriterion("delete_flag not in", values, "delete_flag");
            return (Criteria) this;
        }

        public Criteria andDelete_flagBetween(Boolean value1, Boolean value2) {
            addCriterion("delete_flag between", value1, value2, "delete_flag");
            return (Criteria) this;
        }

        public Criteria andDelete_flagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("delete_flag not between", value1, value2, "delete_flag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mst_device
     *
     * @mbg.generated do_not_delete_during_merge Tue Apr 16 09:00:42 JST 2024
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mst_device
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}