package com.example.demo.domain.model;

import java.util.Date;

public class MstDevice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_device.device_no
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    private String device_no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_device.maker
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    private String maker;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_device.os
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    private String os;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_device.memory
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    private String memory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_device.capacity
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    private String capacity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_device.graphic_board
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    private String graphic_board;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_device.storage_locate
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    private String storage_locate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_device.broken
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    private Boolean broken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_device.lease_flag
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    private Boolean lease_flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_device.lease_start_date
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    private Date lease_start_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_device.lease_deadline_date
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    private Date lease_deadline_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_device.lease_employee_no
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    private String lease_employee_no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_device.remarks
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_device.inventory_date
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    private Date inventory_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_device.register_date
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    private Date register_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_device.update_date
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    private Date update_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_device.delete_flag
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    private Boolean delete_flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_device.device_no
     *
     * @return the value of mst_device.device_no
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    public String getDevice_no() {
        return device_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_device.device_no
     *
     * @param device_no the value for mst_device.device_no
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    public void setDevice_no(String device_no) {
        this.device_no = device_no == null ? null : device_no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_device.maker
     *
     * @return the value of mst_device.maker
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    public String getMaker() {
        return maker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_device.maker
     *
     * @param maker the value for mst_device.maker
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    public void setMaker(String maker) {
        this.maker = maker == null ? null : maker.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_device.os
     *
     * @return the value of mst_device.os
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    public String getOs() {
        return os;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_device.os
     *
     * @param os the value for mst_device.os
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    public void setOs(String os) {
        this.os = os == null ? null : os.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_device.memory
     *
     * @return the value of mst_device.memory
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    public String getMemory() {
        return memory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_device.memory
     *
     * @param memory the value for mst_device.memory
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    public void setMemory(String memory) {
        this.memory = memory == null ? null : memory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_device.capacity
     *
     * @return the value of mst_device.capacity
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    public String getCapacity() {
        return capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_device.capacity
     *
     * @param capacity the value for mst_device.capacity
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    public void setCapacity(String capacity) {
        this.capacity = capacity == null ? null : capacity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_device.graphic_board
     *
     * @return the value of mst_device.graphic_board
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    public String getGraphic_board() {
        return graphic_board;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_device.graphic_board
     *
     * @param graphic_board the value for mst_device.graphic_board
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    public void setGraphic_board(String graphic_board) {
        this.graphic_board = graphic_board == null ? null : graphic_board.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_device.storage_locate
     *
     * @return the value of mst_device.storage_locate
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    public String getStorage_locate() {
        return storage_locate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_device.storage_locate
     *
     * @param storage_locate the value for mst_device.storage_locate
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    public void setStorage_locate(String storage_locate) {
        this.storage_locate = storage_locate == null ? null : storage_locate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_device.broken
     *
     * @return the value of mst_device.broken
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    public Boolean getBroken() {
        return broken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_device.broken
     *
     * @param broken the value for mst_device.broken
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    public void setBroken(Boolean broken) {
        this.broken = broken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_device.lease_flag
     *
     * @return the value of mst_device.lease_flag
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    public Boolean getLease_flag() {
        return lease_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_device.lease_flag
     *
     * @param lease_flag the value for mst_device.lease_flag
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    public void setLease_flag(Boolean lease_flag) {
        this.lease_flag = lease_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_device.lease_start_date
     *
     * @return the value of mst_device.lease_start_date
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    public Date getLease_start_date() {
        return lease_start_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_device.lease_start_date
     *
     * @param lease_start_date the value for mst_device.lease_start_date
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    public void setLease_start_date(Date lease_start_date) {
        this.lease_start_date = lease_start_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_device.lease_deadline_date
     *
     * @return the value of mst_device.lease_deadline_date
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    public Date getLease_deadline_date() {
        return lease_deadline_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_device.lease_deadline_date
     *
     * @param lease_deadline_date the value for mst_device.lease_deadline_date
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    public void setLease_deadline_date(Date lease_deadline_date) {
        this.lease_deadline_date = lease_deadline_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_device.lease_employee_no
     *
     * @return the value of mst_device.lease_employee_no
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    public String getLease_employee_no() {
        return lease_employee_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_device.lease_employee_no
     *
     * @param lease_employee_no the value for mst_device.lease_employee_no
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    public void setLease_employee_no(String lease_employee_no) {
        this.lease_employee_no = lease_employee_no == null ? null : lease_employee_no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_device.remarks
     *
     * @return the value of mst_device.remarks
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_device.remarks
     *
     * @param remarks the value for mst_device.remarks
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_device.inventory_date
     *
     * @return the value of mst_device.inventory_date
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    public Date getInventory_date() {
        return inventory_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_device.inventory_date
     *
     * @param inventory_date the value for mst_device.inventory_date
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    public void setInventory_date(Date inventory_date) {
        this.inventory_date = inventory_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_device.register_date
     *
     * @return the value of mst_device.register_date
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    public Date getRegister_date() {
        return register_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_device.register_date
     *
     * @param register_date the value for mst_device.register_date
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    public void setRegister_date(Date register_date) {
        this.register_date = register_date;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_device.update_date
     *
     * @return the value of mst_device.update_date
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    public Date getUpdate_date() {
        return update_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_device.update_date
     *
     * @param update_date the value for mst_device.update_date
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    public void setUpdate_date(Date update_date) {
        this.update_date = update_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_device.delete_flag
     *
     * @return the value of mst_device.delete_flag
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    public Boolean getDelete_flag() {
        return delete_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_device.delete_flag
     *
     * @param delete_flag the value for mst_device.delete_flag
     *
     * @mbg.generated Tue Apr 16 09:00:42 JST 2024
     */
    public void setDelete_flag(Boolean delete_flag) {
        this.delete_flag = delete_flag;
    }

    private String name;
    
	public String getName() {
		// TODO Auto-generated method stub
		return name;
	}
}