package com.example.demo.domain.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class MstUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mst_user
     *
     * @mbg.generated Tue Apr 16 08:58:15 JST 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mst_user
     *
     * @mbg.generated Tue Apr 16 08:58:15 JST 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mst_user
     *
     * @mbg.generated Tue Apr 16 08:58:15 JST 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated Tue Apr 16 08:58:15 JST 2024
     */
    public MstUserExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated Tue Apr 16 08:58:15 JST 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated Tue Apr 16 08:58:15 JST 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated Tue Apr 16 08:58:15 JST 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated Tue Apr 16 08:58:15 JST 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated Tue Apr 16 08:58:15 JST 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated Tue Apr 16 08:58:15 JST 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated Tue Apr 16 08:58:15 JST 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated Tue Apr 16 08:58:15 JST 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated Tue Apr 16 08:58:15 JST 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mst_user
     *
     * @mbg.generated Tue Apr 16 08:58:15 JST 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mst_user
     *
     * @mbg.generated Tue Apr 16 08:58:15 JST 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andEmployee_noIsNull() {
            addCriterion("employee_no is null");
            return (Criteria) this;
        }

        public Criteria andEmployee_noIsNotNull() {
            addCriterion("employee_no is not null");
            return (Criteria) this;
        }

        public Criteria andEmployee_noEqualTo(String value) {
            addCriterion("employee_no =", value, "employee_no");
            return (Criteria) this;
        }

        public Criteria andEmployee_noNotEqualTo(String value) {
            addCriterion("employee_no <>", value, "employee_no");
            return (Criteria) this;
        }

        public Criteria andEmployee_noGreaterThan(String value) {
            addCriterion("employee_no >", value, "employee_no");
            return (Criteria) this;
        }

        public Criteria andEmployee_noGreaterThanOrEqualTo(String value) {
            addCriterion("employee_no >=", value, "employee_no");
            return (Criteria) this;
        }

        public Criteria andEmployee_noLessThan(String value) {
            addCriterion("employee_no <", value, "employee_no");
            return (Criteria) this;
        }

        public Criteria andEmployee_noLessThanOrEqualTo(String value) {
            addCriterion("employee_no <=", value, "employee_no");
            return (Criteria) this;
        }

        public Criteria andEmployee_noLike(String value) {
            addCriterion("employee_no like", value, "employee_no");
            return (Criteria) this;
        }

        public Criteria andEmployee_noNotLike(String value) {
            addCriterion("employee_no not like", value, "employee_no");
            return (Criteria) this;
        }

        public Criteria andEmployee_noIn(List<String> values) {
            addCriterion("employee_no in", values, "employee_no");
            return (Criteria) this;
        }

        public Criteria andEmployee_noNotIn(List<String> values) {
            addCriterion("employee_no not in", values, "employee_no");
            return (Criteria) this;
        }

        public Criteria andEmployee_noBetween(String value1, String value2) {
            addCriterion("employee_no between", value1, value2, "employee_no");
            return (Criteria) this;
        }

        public Criteria andEmployee_noNotBetween(String value1, String value2) {
            addCriterion("employee_no not between", value1, value2, "employee_no");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andName_kanaIsNull() {
            addCriterion("name_kana is null");
            return (Criteria) this;
        }

        public Criteria andName_kanaIsNotNull() {
            addCriterion("name_kana is not null");
            return (Criteria) this;
        }

        public Criteria andName_kanaEqualTo(String value) {
            addCriterion("name_kana =", value, "name_kana");
            return (Criteria) this;
        }

        public Criteria andName_kanaNotEqualTo(String value) {
            addCriterion("name_kana <>", value, "name_kana");
            return (Criteria) this;
        }

        public Criteria andName_kanaGreaterThan(String value) {
            addCriterion("name_kana >", value, "name_kana");
            return (Criteria) this;
        }

        public Criteria andName_kanaGreaterThanOrEqualTo(String value) {
            addCriterion("name_kana >=", value, "name_kana");
            return (Criteria) this;
        }

        public Criteria andName_kanaLessThan(String value) {
            addCriterion("name_kana <", value, "name_kana");
            return (Criteria) this;
        }

        public Criteria andName_kanaLessThanOrEqualTo(String value) {
            addCriterion("name_kana <=", value, "name_kana");
            return (Criteria) this;
        }

        public Criteria andName_kanaLike(String value) {
            addCriterion("name_kana like", value, "name_kana");
            return (Criteria) this;
        }

        public Criteria andName_kanaNotLike(String value) {
            addCriterion("name_kana not like", value, "name_kana");
            return (Criteria) this;
        }

        public Criteria andName_kanaIn(List<String> values) {
            addCriterion("name_kana in", values, "name_kana");
            return (Criteria) this;
        }

        public Criteria andName_kanaNotIn(List<String> values) {
            addCriterion("name_kana not in", values, "name_kana");
            return (Criteria) this;
        }

        public Criteria andName_kanaBetween(String value1, String value2) {
            addCriterion("name_kana between", value1, value2, "name_kana");
            return (Criteria) this;
        }

        public Criteria andName_kanaNotBetween(String value1, String value2) {
            addCriterion("name_kana not between", value1, value2, "name_kana");
            return (Criteria) this;
        }

        public Criteria andDepartmentIsNull() {
            addCriterion("department is null");
            return (Criteria) this;
        }

        public Criteria andDepartmentIsNotNull() {
            addCriterion("department is not null");
            return (Criteria) this;
        }

        public Criteria andDepartmentEqualTo(String value) {
            addCriterion("department =", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentNotEqualTo(String value) {
            addCriterion("department <>", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentGreaterThan(String value) {
            addCriterion("department >", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentGreaterThanOrEqualTo(String value) {
            addCriterion("department >=", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentLessThan(String value) {
            addCriterion("department <", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentLessThanOrEqualTo(String value) {
            addCriterion("department <=", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentLike(String value) {
            addCriterion("department like", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentNotLike(String value) {
            addCriterion("department not like", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentIn(List<String> values) {
            addCriterion("department in", values, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentNotIn(List<String> values) {
            addCriterion("department not in", values, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentBetween(String value1, String value2) {
            addCriterion("department between", value1, value2, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentNotBetween(String value1, String value2) {
            addCriterion("department not between", value1, value2, "department");
            return (Criteria) this;
        }

        public Criteria andTel_noIsNull() {
            addCriterion("tel_no is null");
            return (Criteria) this;
        }

        public Criteria andTel_noIsNotNull() {
            addCriterion("tel_no is not null");
            return (Criteria) this;
        }

        public Criteria andTel_noEqualTo(String value) {
            addCriterion("tel_no =", value, "tel_no");
            return (Criteria) this;
        }

        public Criteria andTel_noNotEqualTo(String value) {
            addCriterion("tel_no <>", value, "tel_no");
            return (Criteria) this;
        }

        public Criteria andTel_noGreaterThan(String value) {
            addCriterion("tel_no >", value, "tel_no");
            return (Criteria) this;
        }

        public Criteria andTel_noGreaterThanOrEqualTo(String value) {
            addCriterion("tel_no >=", value, "tel_no");
            return (Criteria) this;
        }

        public Criteria andTel_noLessThan(String value) {
            addCriterion("tel_no <", value, "tel_no");
            return (Criteria) this;
        }

        public Criteria andTel_noLessThanOrEqualTo(String value) {
            addCriterion("tel_no <=", value, "tel_no");
            return (Criteria) this;
        }

        public Criteria andTel_noLike(String value) {
            addCriterion("tel_no like", value, "tel_no");
            return (Criteria) this;
        }

        public Criteria andTel_noNotLike(String value) {
            addCriterion("tel_no not like", value, "tel_no");
            return (Criteria) this;
        }

        public Criteria andTel_noIn(List<String> values) {
            addCriterion("tel_no in", values, "tel_no");
            return (Criteria) this;
        }

        public Criteria andTel_noNotIn(List<String> values) {
            addCriterion("tel_no not in", values, "tel_no");
            return (Criteria) this;
        }

        public Criteria andTel_noBetween(String value1, String value2) {
            addCriterion("tel_no between", value1, value2, "tel_no");
            return (Criteria) this;
        }

        public Criteria andTel_noNotBetween(String value1, String value2) {
            addCriterion("tel_no not between", value1, value2, "tel_no");
            return (Criteria) this;
        }

        public Criteria andMail_adressIsNull() {
            addCriterion("mail_adress is null");
            return (Criteria) this;
        }

        public Criteria andMail_adressIsNotNull() {
            addCriterion("mail_adress is not null");
            return (Criteria) this;
        }

        public Criteria andMail_adressEqualTo(String value) {
            addCriterion("mail_adress =", value, "mail_adress");
            return (Criteria) this;
        }

        public Criteria andMail_adressNotEqualTo(String value) {
            addCriterion("mail_adress <>", value, "mail_adress");
            return (Criteria) this;
        }

        public Criteria andMail_adressGreaterThan(String value) {
            addCriterion("mail_adress >", value, "mail_adress");
            return (Criteria) this;
        }

        public Criteria andMail_adressGreaterThanOrEqualTo(String value) {
            addCriterion("mail_adress >=", value, "mail_adress");
            return (Criteria) this;
        }

        public Criteria andMail_adressLessThan(String value) {
            addCriterion("mail_adress <", value, "mail_adress");
            return (Criteria) this;
        }

        public Criteria andMail_adressLessThanOrEqualTo(String value) {
            addCriterion("mail_adress <=", value, "mail_adress");
            return (Criteria) this;
        }

        public Criteria andMail_adressLike(String value) {
            addCriterion("mail_adress like", value, "mail_adress");
            return (Criteria) this;
        }

        public Criteria andMail_adressNotLike(String value) {
            addCriterion("mail_adress not like", value, "mail_adress");
            return (Criteria) this;
        }

        public Criteria andMail_adressIn(List<String> values) {
            addCriterion("mail_adress in", values, "mail_adress");
            return (Criteria) this;
        }

        public Criteria andMail_adressNotIn(List<String> values) {
            addCriterion("mail_adress not in", values, "mail_adress");
            return (Criteria) this;
        }

        public Criteria andMail_adressBetween(String value1, String value2) {
            addCriterion("mail_adress between", value1, value2, "mail_adress");
            return (Criteria) this;
        }

        public Criteria andMail_adressNotBetween(String value1, String value2) {
            addCriterion("mail_adress not between", value1, value2, "mail_adress");
            return (Criteria) this;
        }

        public Criteria andAgeIsNull() {
            addCriterion("age is null");
            return (Criteria) this;
        }

        public Criteria andAgeIsNotNull() {
            addCriterion("age is not null");
            return (Criteria) this;
        }

        public Criteria andAgeEqualTo(Integer value) {
            addCriterion("age =", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotEqualTo(Integer value) {
            addCriterion("age <>", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThan(Integer value) {
            addCriterion("age >", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("age >=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThan(Integer value) {
            addCriterion("age <", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThanOrEqualTo(Integer value) {
            addCriterion("age <=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeIn(List<Integer> values) {
            addCriterion("age in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotIn(List<Integer> values) {
            addCriterion("age not in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeBetween(Integer value1, Integer value2) {
            addCriterion("age between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotBetween(Integer value1, Integer value2) {
            addCriterion("age not between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andGenderIsNull() {
            addCriterion("gender is null");
            return (Criteria) this;
        }

        public Criteria andGenderIsNotNull() {
            addCriterion("gender is not null");
            return (Criteria) this;
        }

        public Criteria andGenderEqualTo(Integer value) {
            addCriterion("gender =", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotEqualTo(Integer value) {
            addCriterion("gender <>", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThan(Integer value) {
            addCriterion("gender >", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThanOrEqualTo(Integer value) {
            addCriterion("gender >=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThan(Integer value) {
            addCriterion("gender <", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThanOrEqualTo(Integer value) {
            addCriterion("gender <=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderIn(List<Integer> values) {
            addCriterion("gender in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotIn(List<Integer> values) {
            addCriterion("gender not in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderBetween(Integer value1, Integer value2) {
            addCriterion("gender between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotBetween(Integer value1, Integer value2) {
            addCriterion("gender not between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andPositionIsNull() {
            addCriterion("position is null");
            return (Criteria) this;
        }

        public Criteria andPositionIsNotNull() {
            addCriterion("position is not null");
            return (Criteria) this;
        }

        public Criteria andPositionEqualTo(String value) {
            addCriterion("position =", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotEqualTo(String value) {
            addCriterion("position <>", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionGreaterThan(String value) {
            addCriterion("position >", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionGreaterThanOrEqualTo(String value) {
            addCriterion("position >=", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionLessThan(String value) {
            addCriterion("position <", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionLessThanOrEqualTo(String value) {
            addCriterion("position <=", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionLike(String value) {
            addCriterion("position like", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotLike(String value) {
            addCriterion("position not like", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionIn(List<String> values) {
            addCriterion("position in", values, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotIn(List<String> values) {
            addCriterion("position not in", values, "position");
            return (Criteria) this;
        }

        public Criteria andPositionBetween(String value1, String value2) {
            addCriterion("position between", value1, value2, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotBetween(String value1, String value2) {
            addCriterion("position not between", value1, value2, "position");
            return (Criteria) this;
        }

        public Criteria andAccount_levelIsNull() {
            addCriterion("account_level is null");
            return (Criteria) this;
        }

        public Criteria andAccount_levelIsNotNull() {
            addCriterion("account_level is not null");
            return (Criteria) this;
        }

        public Criteria andAccount_levelEqualTo(String value) {
            addCriterion("account_level =", value, "account_level");
            return (Criteria) this;
        }

        public Criteria andAccount_levelNotEqualTo(String value) {
            addCriterion("account_level <>", value, "account_level");
            return (Criteria) this;
        }

        public Criteria andAccount_levelGreaterThan(String value) {
            addCriterion("account_level >", value, "account_level");
            return (Criteria) this;
        }

        public Criteria andAccount_levelGreaterThanOrEqualTo(String value) {
            addCriterion("account_level >=", value, "account_level");
            return (Criteria) this;
        }

        public Criteria andAccount_levelLessThan(String value) {
            addCriterion("account_level <", value, "account_level");
            return (Criteria) this;
        }

        public Criteria andAccount_levelLessThanOrEqualTo(String value) {
            addCriterion("account_level <=", value, "account_level");
            return (Criteria) this;
        }

        public Criteria andAccount_levelLike(String value) {
            addCriterion("account_level like", value, "account_level");
            return (Criteria) this;
        }

        public Criteria andAccount_levelNotLike(String value) {
            addCriterion("account_level not like", value, "account_level");
            return (Criteria) this;
        }

        public Criteria andAccount_levelIn(List<String> values) {
            addCriterion("account_level in", values, "account_level");
            return (Criteria) this;
        }

        public Criteria andAccount_levelNotIn(List<String> values) {
            addCriterion("account_level not in", values, "account_level");
            return (Criteria) this;
        }

        public Criteria andAccount_levelBetween(String value1, String value2) {
            addCriterion("account_level between", value1, value2, "account_level");
            return (Criteria) this;
        }

        public Criteria andAccount_levelNotBetween(String value1, String value2) {
            addCriterion("account_level not between", value1, value2, "account_level");
            return (Criteria) this;
        }

        public Criteria andRetire_dateIsNull() {
            addCriterion("retire_date is null");
            return (Criteria) this;
        }

        public Criteria andRetire_dateIsNotNull() {
            addCriterion("retire_date is not null");
            return (Criteria) this;
        }

        public Criteria andRetire_dateEqualTo(Date value) {
            addCriterionForJDBCDate("retire_date =", value, "retire_date");
            return (Criteria) this;
        }

        public Criteria andRetire_dateNotEqualTo(Date value) {
            addCriterionForJDBCDate("retire_date <>", value, "retire_date");
            return (Criteria) this;
        }

        public Criteria andRetire_dateGreaterThan(Date value) {
            addCriterionForJDBCDate("retire_date >", value, "retire_date");
            return (Criteria) this;
        }

        public Criteria andRetire_dateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("retire_date >=", value, "retire_date");
            return (Criteria) this;
        }

        public Criteria andRetire_dateLessThan(Date value) {
            addCriterionForJDBCDate("retire_date <", value, "retire_date");
            return (Criteria) this;
        }

        public Criteria andRetire_dateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("retire_date <=", value, "retire_date");
            return (Criteria) this;
        }

        public Criteria andRetire_dateIn(List<Date> values) {
            addCriterionForJDBCDate("retire_date in", values, "retire_date");
            return (Criteria) this;
        }

        public Criteria andRetire_dateNotIn(List<Date> values) {
            addCriterionForJDBCDate("retire_date not in", values, "retire_date");
            return (Criteria) this;
        }

        public Criteria andRetire_dateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("retire_date between", value1, value2, "retire_date");
            return (Criteria) this;
        }

        public Criteria andRetire_dateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("retire_date not between", value1, value2, "retire_date");
            return (Criteria) this;
        }

        public Criteria andRegister_dateIsNull() {
            addCriterion("register_date is null");
            return (Criteria) this;
        }

        public Criteria andRegister_dateIsNotNull() {
            addCriterion("register_date is not null");
            return (Criteria) this;
        }

        public Criteria andRegister_dateEqualTo(Date value) {
            addCriterionForJDBCDate("register_date =", value, "register_date");
            return (Criteria) this;
        }

        public Criteria andRegister_dateNotEqualTo(Date value) {
            addCriterionForJDBCDate("register_date <>", value, "register_date");
            return (Criteria) this;
        }

        public Criteria andRegister_dateGreaterThan(Date value) {
            addCriterionForJDBCDate("register_date >", value, "register_date");
            return (Criteria) this;
        }

        public Criteria andRegister_dateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("register_date >=", value, "register_date");
            return (Criteria) this;
        }

        public Criteria andRegister_dateLessThan(Date value) {
            addCriterionForJDBCDate("register_date <", value, "register_date");
            return (Criteria) this;
        }

        public Criteria andRegister_dateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("register_date <=", value, "register_date");
            return (Criteria) this;
        }

        public Criteria andRegister_dateIn(List<Date> values) {
            addCriterionForJDBCDate("register_date in", values, "register_date");
            return (Criteria) this;
        }

        public Criteria andRegister_dateNotIn(List<Date> values) {
            addCriterionForJDBCDate("register_date not in", values, "register_date");
            return (Criteria) this;
        }

        public Criteria andRegister_dateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("register_date between", value1, value2, "register_date");
            return (Criteria) this;
        }

        public Criteria andRegister_dateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("register_date not between", value1, value2, "register_date");
            return (Criteria) this;
        }

        public Criteria andUpdate_dateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdate_dateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdate_dateEqualTo(Date value) {
            addCriterionForJDBCDate("update_date =", value, "update_date");
            return (Criteria) this;
        }

        public Criteria andUpdate_dateNotEqualTo(Date value) {
            addCriterionForJDBCDate("update_date <>", value, "update_date");
            return (Criteria) this;
        }

        public Criteria andUpdate_dateGreaterThan(Date value) {
            addCriterionForJDBCDate("update_date >", value, "update_date");
            return (Criteria) this;
        }

        public Criteria andUpdate_dateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("update_date >=", value, "update_date");
            return (Criteria) this;
        }

        public Criteria andUpdate_dateLessThan(Date value) {
            addCriterionForJDBCDate("update_date <", value, "update_date");
            return (Criteria) this;
        }

        public Criteria andUpdate_dateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("update_date <=", value, "update_date");
            return (Criteria) this;
        }

        public Criteria andUpdate_dateIn(List<Date> values) {
            addCriterionForJDBCDate("update_date in", values, "update_date");
            return (Criteria) this;
        }

        public Criteria andUpdate_dateNotIn(List<Date> values) {
            addCriterionForJDBCDate("update_date not in", values, "update_date");
            return (Criteria) this;
        }

        public Criteria andUpdate_dateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("update_date between", value1, value2, "update_date");
            return (Criteria) this;
        }

        public Criteria andUpdate_dateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("update_date not between", value1, value2, "update_date");
            return (Criteria) this;
        }

        public Criteria andDelete_flagIsNull() {
            addCriterion("delete_flag is null");
            return (Criteria) this;
        }

        public Criteria andDelete_flagIsNotNull() {
            addCriterion("delete_flag is not null");
            return (Criteria) this;
        }

        public Criteria andDelete_flagEqualTo(Boolean value) {
            addCriterion("delete_flag =", value, "delete_flag");
            return (Criteria) this;
        }

        public Criteria andDelete_flagNotEqualTo(Boolean value) {
            addCriterion("delete_flag <>", value, "delete_flag");
            return (Criteria) this;
        }

        public Criteria andDelete_flagGreaterThan(Boolean value) {
            addCriterion("delete_flag >", value, "delete_flag");
            return (Criteria) this;
        }

        public Criteria andDelete_flagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("delete_flag >=", value, "delete_flag");
            return (Criteria) this;
        }

        public Criteria andDelete_flagLessThan(Boolean value) {
            addCriterion("delete_flag <", value, "delete_flag");
            return (Criteria) this;
        }

        public Criteria andDelete_flagLessThanOrEqualTo(Boolean value) {
            addCriterion("delete_flag <=", value, "delete_flag");
            return (Criteria) this;
        }

        public Criteria andDelete_flagIn(List<Boolean> values) {
            addCriterion("delete_flag in", values, "delete_flag");
            return (Criteria) this;
        }

        public Criteria andDelete_flagNotIn(List<Boolean> values) {
            addCriterion("delete_flag not in", values, "delete_flag");
            return (Criteria) this;
        }

        public Criteria andDelete_flagBetween(Boolean value1, Boolean value2) {
            addCriterion("delete_flag between", value1, value2, "delete_flag");
            return (Criteria) this;
        }

        public Criteria andDelete_flagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("delete_flag not between", value1, value2, "delete_flag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mst_user
     *
     * @mbg.generated do_not_delete_during_merge Tue Apr 16 08:58:15 JST 2024
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mst_user
     *
     * @mbg.generated Tue Apr 16 08:58:15 JST 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}